eis/urls.py
from django.conf.urls import patterns, include, url


from django.contrib import admin

admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'eis.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^emp/', include('emp.urls',namespace="emp")),
    url(r'^admin/', include(admin.site.urls)),
)

emp/urls.py
from django.conf.urls import patterns,url
from emp.views import Department_List,Employee_List
from emp import views
from rest_framework.urlpatterns import format_suffix_patterns
from rest_framework import renderers
dep_list = Department_List.as_view({
    'get': 'list',
    'post': 'create'
},)
dep_detail = Department_List.as_view({
    'get': 'retrieve',
    'put': 'update',
    'patch': 'partial_update',
    'delete': 'destroy'
})
emp_list = Employee_List.as_view({
    'get': 'list',
    'post': 'create'
},)
emp_detail = Employee_List.as_view({
    'get': 'retrieve',
    'put': 'update',
    'patch': 'partial_update',
    'delete': 'destroy'
})
urlpatterns=patterns('',url(r'^$',views.IndexView.as_view(), name="index"),
                        url(r'^list/$', views.List.as_view(), name="List"),
                        url(r'^list1/$',views.List1.as_view(),name="List1"),
                        url(r'^new/$', 'emp.views.new', name="New"),
                       # url(r'^new1/$',views.New1.as_view(), name="New1"),
                      #  url(r'^editDep/$', 'emp.views.editDep', name="EditD"),
                        url(r'^editemp/$', 'emp.views.editemp', name="EditEmp"),
                       # url(r'^delete/(\d+)/$', 'emp.views.delete1',name="Delete"),
                       # url(r'^deldep/(\d+)/$', 'emp.views.deldep',name="Deldep"),
                        url(r'^view/(\d+)/$', 'emp.views.view',name="View"),
                        #url(r'^viewdetail/(\d+)/$', 'emp.views.viewdetail',name="Viewdetail"),
                        #url(r'^edit1/(\d+)/$', 'emp.views.edit1',name="Edit1"),
                        url(r'^edite/(\d+)/$', 'emp.views.edite',name="Edite"),
                        url(r'^department/$',dep_list,name='department'),
                        url(r'^department/(?P<pk>[0-9]+)/$',dep_detail,name='department1'),
                        url(r'^employee/$',emp_list,name='employee'),
                        url(r'^employee/(?P<pk>[0-9]+)/$',emp_detail,name='employee1'),
                     )
#urlpatterns = format_suffix_patterns(urlpatterns)

emp/models.py
from django.db import models

class Department(models.Model):
    department_id=models.AutoField(primary_key=True)
    department_name=models.CharField(max_length=200)

    def __unicode__(self):
        return self.department_name

class Employee(models.Model):
    employee_id=models.AutoField(primary_key=True)
    ename=models.CharField(max_length=200)
    age=models.IntegerField(default=0)
    emailid=models.EmailField(max_length=200)
    mobno=models.IntegerField()
    designation=models.CharField(max_length=20)
    department=models.ForeignKey(Department, on_delete=models.CASCADE)

emp/forms.py
from django import forms
from emp.models import Department

class NewEmpForm(forms.Form):
    ena = forms.CharField(label='Name', max_length=100,widget=forms.TextInput(attrs={'class':'c1'}))
    age = forms.CharField(label='Age', max_length=100)
    email = forms.EmailField(label='Email id', max_length=100)
    mob=forms.CharField(label='Mob no',widget=forms.TextInput(attrs={'class':'c2'}))
    designation = forms.CharField(label='Designation', max_length=100)
    department=forms.ModelChoiceField(label='Department',queryset=Department.objects.all(), to_field_name='department_name', empty_label="select")

#class NewDepForm(forms.Form):
 #   d1 = forms.CharField(label='Department Name', max_length=100,widget=forms.TextInput(attrs={'class':'department'}))

emp/views.py
from bsddb import db
from django.http import HttpResponse, HttpResponseRedirect

from django.shortcuts import render, get_object_or_404
from django.core.urlresolvers import reverse
from django.views import generic
from emp.forms import NewEmpForm
from emp.models import Employee,Department
from emp.serializers import DepSerializer, EmployeeSerializer
from rest_framework.response import Response
from rest_framework.decorators import api_view,action,link
from rest_framework.decorators import APIView
from django.http import Http404
from rest_framework import mixins
from rest_framework import renderers
from rest_framework.reverse import reverse
from rest_framework import generics
from rest_framework import viewsets
from rest_framework.request import Request

class Department_List(viewsets.ModelViewSet):
    model = Department
    queryset = Department.objects.all()
    serializer_class = DepSerializer

class Employee_List(viewsets.ModelViewSet):
    model = Employee
    queryset = Employee.objects.all()
    serializer_class = EmployeeSerializer

class IndexView(generic.TemplateView):
    template_name = 'emp/index.html'


class List1(generic.ListView):
  #  context_object_name = 'depl'
    template_name = 'emp/list1.html'
    model=Department
   # def get_queryset(self):
    #   return Department.objects.all()

class List(generic.ListView):
    context_object_name = 'empl'
    template_name = 'emp/list.html'
    def get_queryset(self):
       return Employee.objects.all()

def new(request):
    if request.method == 'POST':

        form = NewEmpForm(request.POST)

        if form.is_valid():
            e1=form.cleaned_data['ena']
            e2=form.cleaned_data['age']
            e3=form.cleaned_data['email']
            e4=form.cleaned_data['mob']
            e5=form.cleaned_data['designation']
            e6=form.cleaned_data['department']
            edet=Employee.objects.create(ename=e1,age=e2,emailid=e3,mobno=e4,designation=e5,department=e6)
            return HttpResponseRedirect(reverse('emp:List'))
    else:
        form = NewEmpForm()

    return render(request, 'emp/new.html', {'form': form, 'd1': Department.objects.all()})


def view(request,id):
   e2=get_object_or_404(Employee,pk=id)
   return render(request,'emp/view.html', {'e2': e2})

def delete1(request, id):
   e1= Employee.objects.get(pk=id)
   e1.delete()
   return HttpResponseRedirect(reverse('emp:List'))
 #  return render(request, 'emp/list.html', {'emp':e1, 'del1_message': "Record succesfully deleted.",})

def edite(request,id):
    e1=Employee.objects.get(pk=id)
    d1=Department.objects.all()
    return render(request, 'emp/edite.html', {'d1': d1, 'e1': e1})

def editemp(request):
    name = request.GET.get('e2')
    name1 = request.GET.get('e3')
    name2 = request.GET.get('e4')
    name3 = request.GET.get('e5')
    name4 = request.GET.get('e6')
    name5 = request.GET.get('e7')
    id1 = request.GET.get('eeid')
    id=Department.objects.get(department_name=name5)
    e1 = Employee.objects.get(pk=id1)
    e1.ename = name; e1.age=name1; e1.emailid=name2; e1.mobno=name3; e1.designation=name4; e1.department_id=id;
    e1.save()
    return HttpResponseRedirect(reverse('emp:List'))

emp/templates/emp/edit1.html
{% extends "base.html" %}
{% block title %}List of Department{% endblock title %}
{% block js %}<script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.3/jquery.min.js"></script>
    <script src="{{ STATIC_URL }}js/department_edit.js"></script>{% endblock js %}
{% block content %}
    <center>
    <hr><hr><hr>
   {% csrf_token %}

    <h2 class="alert-warning">Edit Department</h2>
    <hr>
    {% if error_message %}<p class="alert-danger"><strong>{{error_message}}</strong></p>{% endif %}
        {% csrf_token %}
        Department:<input type="text" maxlength="30" name="dept" id="id_department" value="{{ d1.department_name }}" class="department" />
    <input type="button" name="back" value="Back" class="btn btn-primary" id="back" />
        <input type="submit" name="update" value="Update" id="{{ d1.id }}" class="update btn btn-primary" />
        <div id="error"></div><br/><br/>


    </form>
        </fieldset>
        </center>
{% endblock content %}

emp/templates/emp/edite.html
{% extends "base.html" %}
{% block title %}Edit Employee detail{% endblock title %}
{% block js %}<script type="text/javascript" src="{{ STATIC_URL }}js/val1.js">
        </script> {% endblock %}
{% block content %}
    <center>
    <hr><hr><hr>
    <h2 class="alert-warning">Edit Employee Details</h2><hr>
        {% csrf_token %}
    <form id="f1" action="{% url 'emp:EditEmp' %}" method="get" onsubmit="return valueChek();" >


       {% csrf_token %}
        <table class="table table-bordered" style="width: 60%">
       <tr><th> Name:</th><td><input type="text" maxlength="30" name="e2" value="{{ e1.ename }}" /></td></tr>
        <tr><th>  Age:</th><td><input type="text" maxlength="30" name="e3" value="{{ e1.age }}" /></td></tr>
       <tr><th>  Email id:</th><td><input type="text" maxlength="30" name="e4" value="{{ e1.emailid }}" /></td></tr>
        <tr><th> Mobile No:</th><td><input type="text" maxlength="30" name="e5" value="{{ e1.mobno }}" /></td></tr>
        <tr><th> Designation:</th><td><input type="text" maxlength="30" name="e6" value="{{ e1.designation }}" /></td></tr>
        <tr><th> Department:</th><td><select name="e7">{% for i in d1 %}
        <option value="{{ i.department_name }}" {%if i.id == e1.department_id%}selected{% endif %}>{{ i.department_name }}</option>
        {% endfor %} </select></td></tr>
            <input type="hidden" value="{{ e1.id }}" name="eeid">
        </table>
        <span class="btn btn-primary"> <a href="{% url 'emp:List' %}" style="color: #ffffff">Back</a></span>
        <input type="submit" name="update" value="Update" class="btn btn-primary" />

    </form>

        </center>
{% endblock content %}

emp/templates/emp/index.html
{% extends "base.html" %}
{% block title %}Home page{% endblock title %}
{% block js %}<script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.3/jquery.min.js"></script>
    <script src="{{ STATIC_URL }}js/index.js"></script>{% endblock js %}
{% block detail %}
    <ul>
        <li class="jumbotron"><a id="list" href="javascript:void(0)">Employee Details</a></li>
        <li class="jumbotron"><a  id="list1" href="javascript:void(0)">Department Details</a></li>
    </ul>
{% endblock detail %}

emp/templates/emp/list.html
{% extends "base.html" %}
{% block title %}List of Employee{% endblock title %}
{% block js %}<script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.3/jquery.min.js"></script >
    <script src="{{ STATIC_URL }}js/list.js"></script>
    {% endblock js %}
{% block content %}
    <center>
    <hr><hr><hr>
    <div id="employeelist">
    <h2 class="alert-warning">List of Employees</h2>
    <table class="table table-bordered" id="emp_list1">
            <tr>

                <th>Name</th>
                <th>Age</th>
                <th>Email_id</th>
                <th>Mob_no</th>
                <th>Designation</th>
                 <th>Department</th>
                <th>View details</th>
                <th>Edit Record</th>
                 <th>Delete Record</th>
            </tr>
    </table>
        <input type="button" name="back" id="back" value="Back" class="btn btn-primary" />
       <input type="button" name="newwmployee" id="newemployee" value="Add New Employee?" class="btn btn-primary" />
 </div>
 <div id="editemployee" style="display: none">
      <h2 class="alert-warning">Edit Employee Details</h2><hr>

        <table class="table table-bordered" style="width: 60%">
       <tr><th> Name:</th><td><input type="text" maxlength="30" name="e2" id="ename1"/><div id="name"></div></td></tr>
        <tr><th>  Age:</th><td><input type="text" maxlength="30" name="e3" id="age1" /><div id="name"></div></td></tr>
       <tr><th>  Email id:</th><td><input type="text" maxlength="30" name="e4" id="email1"/><div id="name"></div></td></tr>
        <tr><th> Mobile No:</th><td><input type="text" maxlength="30" name="e5" id="mob1"/><div id="name"></div></td></tr>
        <tr><th> Designation:</th><td><input type="text" maxlength="30" name="e6" id="designation1"/><div id="name"></div></td></tr>
        <tr><th> Department:</th><td><select name="e7" id="dropdepartment"></select>
        </td></tr>

        </table>
       <input type="button" name="back" id="back1" value="Back" class="btn btn-primary" />
        <input type="button" name="update" value="Update" class="btn btn-primary" />

 </div>
    <div id="viewemployee" style="display: none">
         <h2 class="alert-warning" id="viewemp"></h2><hr>

    <table class="table table-striped" id="viewtable" border="1" style="width: 60%">
        <tr></tr><tr></tr>
        <tr><th>Name</th><th id="ename2"></th></tr>
        <tr><th>Age</th><th id="age2"></th></tr>
        <tr><th>Email id</th><th id="email2"></th></tr>
        <tr><th>Mobile No</th><th id="mob2"></th></tr>
        <tr><th>Designation</th><th id="designation2"></th></tr>
        <tr><th>Department</th><th id="department2"></th></tr>
    </table>
    <input type="button" name="back" id="back2" value="Back" class="btn btn-primary" />
    </div>
 <div id="newemp" style="display: none">
      <h2 class="alert-warning">Edit Employee Details</h2><hr>

        <table class="table table-bordered" style="width: 60%">
       <tr><th> Name:</th><td><input type="text" maxlength="30" name="e2" id="ename_new"/><div id="new1"></div></td></tr>
        <tr><th>  Age:</th><td><input type="text" maxlength="30" name="e3" id="age_new" /><div id="new2"></div></td></tr>
       <tr><th>  Email id:</th><td><input type="text" maxlength="30" name="e4" id="email_new"/><div id="new3"></div></td></tr>
        <tr><th> Mobile No:</th><td><input type="text" maxlength="30" name="e5" id="mob_new"/><div id="new4"></div></td></tr>
        <tr><th> Designation:</th><td><input type="text" maxlength="30" name="e6" id="designation_new"/><div id="new5"></div></td></tr>
        <tr><th> Department:</th><td><select name="e7" id="dropdepartment1"></select>
        </td></tr>

        </table>
       <input type="button" name="back" id="back3" value="Back" class="btn btn-primary" />
        <input type="button" name="add" id="add" value="Add" class="btn btn-primary" />
        <input type="button" name="Reset" value="reset" id="reset_emp" class="btn btn-primary" />

 </div>
    <div id="newerror" style="display: none">
        <pre class="alert-info">Currently there is no department. Add department first.</pre>

    </div>
</center>
{% endblock content %}

emp/templates/emp/list1.html
{% extends "base.html" %}
{% block title %}List of Department{% endblock title %}
{% block js %}<script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.3/jquery.min.js"></script >
    <script src="{{ STATIC_URL }}js/list1.js"></script>
    {% endblock js %}
{% block content %}
    <center>
    <hr><hr><hr>
        <div id="listdepartment">
     <h2 class="alert-warning">List of Department</h2><hr>

        <div id="error"></div>
        <table class="table table-bordered" id="department_list">
            <tr>

                <th>Department_Name</th>
                <th>View Employee details</th>
                <th>Edit details</th>
                <th> Delete??</th>
            </tr>
        </table>
        <b><div id="noData"></div></b><br/><br/>
    <input type="button" name="back" value="Back" class="btn btn-primary" id="back" />
    <input type="button" name="submit1" id="new" class="btn btn-primary" value="Add New Department?" />
    </div>
    <div id="adddepartment" style="display: none;">
    <h2 class="alert-warning">Add New Departmnet</h2><hr>
        <table>
    <tr><td><label for="id_department">Department Name:</label></td><td><input type="text" name="department" id="id_department" value=" " class="department" /></td></tr>
        <tr><td></td><td><div id="error1"></div></td></tr>
            </table><br/><br/>


        <input type="button" name="back" value="Back" class="btn btn-primary" id="back1" />
        <input type="button" name="add" value="Add" class="btn btn-primary" id="add" />
        <input type="button" name="reset" value="RESET" id="reset_dept" class="btn btn-primary" />
    </div>
    <div id="updatedepartment" style="display: none">
        {% csrf_token %}
        <h2 class="alert-warning">Edit Department</h2>
        Department:<input type="text" maxlength="30" name="dept" id="id_department1"  class="department" />
        <input type="button" name="back" value="Back" class="btn btn-primary" id="back2" />
        <input type="button" name="update" value="Update" class="update btn btn-primary" />
        <div id="error2"></div>
        <br/><br/>
    </div>
     <div id="viewdetails" style="display: none">
        <h2 class="alert-warning" id="viewdet"></h2>
        <table class="table table-bordered" id="emp_list">
            <tr>

                <th>Name</th>
                <th>Age</th>
                <th>Email_id</th>
                <th>Mob_no</th>
                <th>Designation</th>
            </tr>
        </table>
         <input type="button" name="back" value="Back" class="btn btn-primary" id="back3" />
     </div>
</center>
{% endblock content %}

emp/templates/emp/new.html
{% extends "base.html" %}

{% block title %}Add New Employee{% endblock title %}
{% block js %}<script type="text/javascript" src="{{ STATIC_URL }}js/val1.js">
        </script> {% endblock %}
{% block content %}
    <center>
    <hr><hr><hr>
    <h2 class="alert-warning">New Employee Detail</h2><hr>
    <form id="f1" action="{% url 'emp:New'%}" method="post" class="navbar-form" onsubmit="return valueChek();">

       {% csrf_token %}

        <table class="table table-bordered" style="width: 60%">
        {% if d1 %}

        {{ form.as_table }}

        </table>
            <div id="error"></div>
        <span class="btn btn-primary"><a href="{% url 'emp:List' %}" style="color: #ffffff">Back</a></span>
        <input type="submit" name="add" value="Add" class="btn btn-primary" />
        <input type="reset" name="reset" value="RESET" class="btn btn-primary"/>

    </form>
        {% else %}
    <pre class="alert-info">
        Currently There is no department yet.
        First add Department details
        Go to <a href='{% url 'emp:index' %}'>Home page</a>
    </pre>
    {% endif %}

    </center>
{% endblock content %}

emp/templates/emp/new1.html
{% extends "base.html" %}
{% block title %}Add New Department{% endblock title %}
{% block js %}<script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.3/jquery.min.js"></script>
    <script src="{{ STATIC_URL }}js/department.js"></script>{% endblock js %}
{% block content %}
    <center>
    <hr><hr><hr>
      {% csrf_token %}

    <h2 class="alert-warning">Add New Departmnet</h2><hr>
        <table>
    <tr><td><label for="id_department">Department Name:</label></td><td><input type="text" name="department" id="id_department" class="department" /></td></tr>
        <tr><td></td><td><div id="error"></div></td></tr>
            </table><br/><br/>


        <input type="button" name="back" value="Back" class="btn btn-primary" id="back" />
        <input type="button" name="add" value="Add" class="btn btn-primary" id="add" />
        <input type="reset" name="reset" value="RESET" class="btn btn-primary" />



        </center>
{% endblock content %}

emp/templates/emp/view.html
{% extends "base.html" %}
{% block title %}List of Employee{% endblock title %}
{% block content %}
    <hr><hr><hr>
   <center>
   <h2 class="alert-warning">Details of Employee</h2><hr>
<form method="post">
    {% csrf_token %}
    <table class="table table-striped" border="1" style="width: 60%">
        <tr></tr><tr></tr>
        <tr><th>Name</th><th>{{ e2.ename }}</th></tr>
        <tr><th>Age</th><th>{{ e2.age }}</th></tr>
        <tr><th>Email id</th><th>{{ e2.emailid }}</th></tr>
        <tr><th>Mobile No</th><th>{{ e2.mobno }}</th></tr>
        <tr><th>Designation</th><th>{{ e2.designation }}</th></tr>
        <tr><th>Department</th><th>{{ e2.department }}</th></tr>
    </table>
    <span class="btn btn-primary"><a href="{% url 'emp:List' %}" style="color: #ffffff">Back</a></span>
    <span class="btn btn-primary"><a href="{% url 'emp:Edite' e2.id %}" style="color: #ffffff">Edit Record</a></span>
    <span class="btn btn-primary"><a href="{% url 'emp:Delete' e2.id %}" style="color: #ffffff">Delete Record</a></span>


</form>
</center>
{% endblock content %}

emp/templates/emp/view1.html
{% extends "base.html" %}
{% block title %}List of Department{% endblock title %}
{% block content %}
    <center>
    <hr><hr><hr>
     <h2 class="alert-warning">Employees of {{department.department_name}} department</h2>
    {% if e3 %}
    <form id="f2">
        {% csrf_token %}
        <table class="table table-bordered">
            <tr>
                <th>Sr.no</th>
                <th>Name</th>
                <th>Age</th>
                <th>Email_id</th>
                <th>Mob_no</th>
                <th>Designation</th>
                <th> </th>

            </tr>
            {% for e3 in e3 %}
            <tr>
                <td>{{ forloop.counter }}</td>
                <td>{{ e3.ename }}</td>
                <td>{{ e3.age }}</td>
                <td>{{ e3.emailid }}</td>
                <td>{{ e3.mobno }}</td>
                <td>{{ e3.designation }}</td>
                <td><a href="{% url 'emp:View' e3.id%}">View Details</a></td>
            </tr><tr></tr><tr></tr>
            {% endfor %}
        </table>
    </form>
    {% else %}
        <br />
    <p class="label-info"> No data found </p><p></p><p></p>
    {% endif %}
      <span class="btn btn-primary"><a href="{% url 'emp:List1' %}" style="color: #ffffff">Back</a></span>
</center>
{% endblock content %}

templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>{% block title %} {% endblock title %}</title>
    {% block js %}{% endblock %}
    <!-- Bootstrap Core CSS -->
    <link href="/static/css/bootstrap.min.css" rel="stylesheet">

    <!-- Custom CSS -->
    <link href="/static/css/half-slider.css" rel="stylesheet">

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->

</head>

<body>
    <hr>

    <!-- Navigation -->
    <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
        <div class="container">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <!--a class="navbar-brand" href="#">Start Bootstrap</a -->
                   <a class="navbar-brand" href="{% url 'emp:index' %}">Employee Information System</a>

            </div>
            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav">
                    <li>
                        <a href="{% url 'emp:List' %}">Employee Details</a>
                    </li>
                    <li>
                        <a href="{% url 'emp:List1' %}">Department Details</a>
                    </li>

                </ul>
            </div>

            <!-- /.navbar-collapse -->
        </div>
        <!-- /.container -->
    </nav>


         {% block content %}
    <!-- Half Page Image Background Carousel Header -->
    <header id="myCarousel" class="carousel slide">

        <!-- Indicators -->
        <ol class="carousel-indicators">
            <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
            <li data-target="#myCarousel" data-slide-to="1"></li>
            <li data-target="#myCarousel" data-slide-to="2"></li>
        </ol>

        <!-- Wrapper for Slides -->
          <div class="carousel-inner">
            <div class="item active">
                <!-- Set the first background image using inline CSS below. -->
                <div class="fill" style="background-image:url('http://placehold.it/1900x1080&text=Team Work');"></div>
                <div class="carousel-caption">
                    <h2>Team Work</h2>
                </div>
            </div>
            <div class="item">
                <!-- Set the second background image using inline CSS below. -->
                <div class="fill" style="background-image:url('http://placehold.it/1900x1080&text=Team Spirit');"></div>
                <div class="carousel-caption">
                    <h2>Team spirit</h2>
                </div>
            </div>
            <div class="item">
                <!-- Set the third background image using inline CSS below. -->
                <div class="fill" style="background-image:url('http://placehold.it/1900x1080&text=Team Goal');"></div>
                <div class="carousel-caption">
                    <h2>Team Goal</h2>
                </div>
            </div>
        </div>


        <!-- Controls -->
        <a class="left carousel-control" href="#myCarousel" data-slide="prev">
            <span class="icon-prev"></span>
        </a>
        <a class="right carousel-control" href="#myCarousel" data-slide="next">
            <span class="icon-next"></span>
        </a>

    </header>

    <!-- Page Content -->
    <div class="container">

        <hr/>
        <div class="row">
            <div class="col-lg-12">
                <h1>Welcome to employee Information System</h1>
                <p>This system manages employees and department details</p>
                {% block detail %}{% endblock  %}
            </div>
        </div>
        {% endblock content %}
        <hr />

        <!-- Footer -->
        <footer class="jumbotron">
            <div class="row">
                <div class="col-lg-12">
                    <p><center>Copyright &copy; Employee Information System 2014</center></p>
                </div>
            </div>
            <!-- /.row -->
        </footer>

    </div>
    <!-- /.container -->

    <!-- jQuery Version 1.11.0 -->
    <script src="{{ STATIC_URL }}js/jquery-1.11.0.js"></script>

    <!-- Bootstrap Core JavaScript -->
    <script src="{{ STATIC_URL }}js/bootstrap.min.js"></script>

    <!-- Script to Activate the Carousel -->
    <script>
    $('.carousel').carousel({
        interval: 5000 //changes the speed
    })
    </script>

</body>

</html>